import { createFileRoute } from "@tanstack/react-router";
import { useDashboard, type Goal } from "../components/dashboard-layout";
import { GoalCardActions, GoalCardMeta } from "../components/dashboard/goal-card";
import { ChevronRightIcon, GoalIcon, PlusIcon } from "../components/dashboard/icons";
import { Tooltip } from "../components/tooltip";

export const Route = createFileRoute("/app/")({
  head: () => ({
    meta: [{ title: "xGoal — Overview" }],
  }),
  component: OverviewPage,
});

function OverviewPage() {
  const { goals, openCreateGoal } = useDashboard();

  return <section className="min-h-screen bg-paper">
    <header className="flex min-h-20 items-center justify-between gap-6 border-b border-line px-5 sm:px-8"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">Workspace</p><h1 className="mt-1 text-xl font-semibold tracking-[-0.04em]">Overview</h1></section><button type="button" onClick={openCreateGoal} className="inline-flex items-center gap-2 rounded-xl bg-blue px-4 py-2.5 text-sm font-bold text-white shadow-sm transition-transform hover:-translate-y-0.5"><PlusIcon />New goal</button></header>
    <section className="mx-auto max-w-6xl space-y-8 p-5 sm:p-8" aria-label="Dashboard content">
      <header><p className="text-sm font-medium text-blue">Your operating system for showing up</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.07em]">Your workspace is ready.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Goals give your work direction. Workflows turn that direction into repeatable action.</p></header>
      <section className="grid gap-4 sm:grid-cols-3" aria-label="Workspace summary"><Metric label="Goals" value={String(goals.length)} detail="Outcomes you are pursuing" /><Metric label="Workflows" value={String(goals.reduce((total, goal) => total + goal.workflowCount, 0))} detail="Ready to deploy" /><Metric label="Permissions" value="0" detail="Review when you create a goal" /></section>
      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.65fr)]"><article className="rounded-3xl border border-line bg-paper p-5 sm:p-7"><header className="flex items-start justify-between gap-4"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted">The foundation</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.05em]">Goals</h2></section><button type="button" onClick={openCreateGoal} className="hidden items-center gap-2 rounded-xl border border-line bg-white px-3 py-2 text-sm font-semibold transition-colors hover:border-ink sm:inline-flex"><PlusIcon />Create</button></header>{goals.length === 0 ? <section className="mt-8 rounded-2xl border border-dashed border-line bg-white px-6 py-12 text-center"><p className="mx-auto grid size-12 place-items-center rounded-2xl bg-blue-pale text-blue"><GoalIcon /></p><h3 className="mt-5 text-xl font-semibold tracking-[-0.04em]">Create the first goal</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted">Describe the outcome you want. xGoal will help turn the prompt into the right permissions, branches, and workflows.</p><button type="button" onClick={openCreateGoal} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue px-4 py-2.5 text-sm font-bold text-white"><PlusIcon />Create a goal</button></section> : <ul className="mt-8 space-y-3">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} />)}</ul>}</article><aside className="rounded-3xl bg-ink p-6 text-white sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-soft">How xGoal works</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.05em]">One goal. Many ways forward.</h2><ol className="mt-8 space-y-6"><li className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-white/10 text-xs font-bold text-blue-soft">01</span><span><strong className="block text-sm">Define the outcome</strong><small className="mt-1 block text-sm leading-5 text-white/60">Start with the result you want to create.</small></span></li><li className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-white/10 text-xs font-bold text-blue-soft">02</span><span><strong className="block text-sm">Review permissions</strong><small className="mt-1 block text-sm leading-5 text-white/60">Control what the agent can read, draft, or publish.</small></span></li><li className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-white/10 text-xs font-bold text-blue-soft">03</span><span><strong className="block text-sm">Deploy workflows</strong><small className="mt-1 block text-sm leading-5 text-white/60">Run multiple workflows from the same goal.</small></span></li></ol></aside></section>
    </section>
  </section>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-2xl border border-line bg-paper p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted">{label}</p><p className="mt-4 text-3xl font-semibold tracking-[-0.06em]">{value}</p><p className="mt-1 text-xs text-muted">{detail}</p></article>; }
function GoalCard({ goal }: { goal: Goal }) { return <li id={`goal-${goal.id}`} className="rounded-2xl border border-line bg-white p-5 transition-colors hover:border-blue sm:p-6"><header className="flex items-start justify-between gap-4"><section className="min-w-0"><h3 className="truncate text-lg font-semibold tracking-[-0.04em]">{goal.title}</h3></section><span className="flex shrink-0 items-center gap-0.5"><GoalCardActions goal={goal} /><Tooltip label={`Open ${goal.title}`} placement="top"><button type="button" className="rounded-lg p-2 text-muted hover:bg-wash hover:text-ink" aria-label={`Open ${goal.title}`}><ChevronRightIcon /></button></Tooltip></span></header><footer className="mt-5 pt-4"><GoalCardMeta goal={goal} /></footer></li>; }
