/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWorkflowWorkflowIdRouteImport } from './routes/app.workflow.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowWorkflowIdRoute = AppWorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/goals'
    | '/app/profile'
    | '/app/workflows'
    | '/auth/callback'
    | '/app/'
    | '/app/workflow/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/goals'
    | '/app/profile'
    | '/app/workflows'
    | '/auth/callback'
    | '/app'
    | '/app/workflow/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/goals'
    | '/app/profile'
    | '/app/workflows'
    | '/auth/callback'
    | '/app/'
    | '/app/workflow/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflow/$workflowId': {
      id: '/app/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/app/workflow/$workflowId'
      preLoaderRoute: typeof AppWorkflowWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGoalsRoute: typeof AppGoalsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowWorkflowIdRoute: typeof AppWorkflowWorkflowIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGoalsRoute: AppGoalsRoute,
  AppProfileRoute: AppProfileRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowWorkflowIdRoute: AppWorkflowWorkflowIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
