/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCreditsRouteImport } from './routes/app.credits'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppWorkflowRouteImport } from './routes/app.workflow'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'
import { Route as ApiBachsWebhookRouteImport } from './routes/api.bachs.webhook'
import { Route as AppGoalsIndexRouteImport } from './routes/app.goals.index'
import { Route as AppGoalsGoalIdRouteImport } from './routes/app.goals.$goalId'
import { Route as AppGoalsNewRouteImport } from './routes/app.goals.new'
import { Route as AppWorkflowsIndexRouteImport } from './routes/app.workflows.index'
import { Route as AppWorkflowsNewRouteImport } from './routes/app.workflows.new'
import { Route as AppGoalsBranchGoalIdRouteImport } from './routes/app.goals.branch.$goalId'
import { Route as AppWorkflowWorkflowIdIndexRouteImport } from './routes/app.workflow.$workflowId.index'
import { Route as AppWorkflowWorkflowIdActivitiesRouteImport } from './routes/app.workflow.$workflowId.activities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBachsWebhookRoute = ApiBachsWebhookRouteImport.update({
  id: '/api/bachs/webhook',
  path: '/api/bachs/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppGoalsNewRoute = AppGoalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppGoalsBranchGoalIdRoute = AppGoalsBranchGoalIdRouteImport.update({
  id: '/branch/$goalId',
  path: '/branch/$goalId',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppWorkflowWorkflowIdIndexRoute =
  AppWorkflowWorkflowIdIndexRouteImport.update({
    id: '/$workflowId/',
    path: '/$workflowId/',
    getParentRoute: () => AppWorkflowRoute,
  } as any)
const AppWorkflowWorkflowIdActivitiesRoute =
  AppWorkflowWorkflowIdActivitiesRouteImport.update({
    id: '/$workflowId/activities',
    path: '/$workflowId/activities',
    getParentRoute: () => AppWorkflowRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/credits': typeof AppCreditsRoute
  '/app/goals': typeof AppGoalsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/workflow': typeof AppWorkflowRouteWithChildren
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/app/': typeof AppIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/api/bachs/webhook': typeof ApiBachsWebhookRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/app/goals/branch/$goalId': typeof AppGoalsBranchGoalIdRoute
  '/app/workflow/$workflowId/activities': typeof AppWorkflowWorkflowIdActivitiesRoute
  '/app/workflow/$workflowId/': typeof AppWorkflowWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workflow': typeof AppWorkflowRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/app': typeof AppIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/api/bachs/webhook': typeof ApiBachsWebhookRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/app/goals': typeof AppGoalsIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
  '/app/goals/branch/$goalId': typeof AppGoalsBranchGoalIdRoute
  '/app/workflow/$workflowId/activities': typeof AppWorkflowWorkflowIdActivitiesRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/credits': typeof AppCreditsRoute
  '/app/goals': typeof AppGoalsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/workflow': typeof AppWorkflowRouteWithChildren
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/app/': typeof AppIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/api/bachs/webhook': typeof ApiBachsWebhookRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/workflows/new': typeof AppWorkflowsNewRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/app/goals/branch/$goalId': typeof AppGoalsBranchGoalIdRoute
  '/app/workflow/$workflowId/activities': typeof AppWorkflowWorkflowIdActivitiesRoute
  '/app/workflow/$workflowId/': typeof AppWorkflowWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/credits'
    | '/app/goals'
    | '/app/profile'
    | '/app/workflow'
    | '/app/workflows'
    | '/auth/callback'
    | '/goals/$goalId'
    | '/app/'
    | '/goals/'
    | '/api/bachs/webhook'
    | '/app/goals/$goalId'
    | '/app/goals/new'
    | '/app/workflows/new'
    | '/app/goals/'
    | '/app/workflows/'
    | '/app/goals/branch/$goalId'
    | '/app/workflow/$workflowId/activities'
    | '/app/workflow/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/credits'
    | '/app/profile'
    | '/app/workflow'
    | '/auth/callback'
    | '/goals/$goalId'
    | '/app'
    | '/goals'
    | '/api/bachs/webhook'
    | '/app/goals/$goalId'
    | '/app/goals/new'
    | '/app/workflows/new'
    | '/app/goals'
    | '/app/workflows'
    | '/app/goals/branch/$goalId'
    | '/app/workflow/$workflowId/activities'
    | '/app/workflow/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/credits'
    | '/app/goals'
    | '/app/profile'
    | '/app/workflow'
    | '/app/workflows'
    | '/auth/callback'
    | '/goals/$goalId'
    | '/app/'
    | '/goals/'
    | '/api/bachs/webhook'
    | '/app/goals/$goalId'
    | '/app/goals/new'
    | '/app/workflows/new'
    | '/app/goals/'
    | '/app/workflows/'
    | '/app/goals/branch/$goalId'
    | '/app/workflow/$workflowId/activities'
    | '/app/workflow/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  ApiBachsWebhookRoute: typeof ApiBachsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credits': {
      id: '/app/credits'
      path: '/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow': {
      id: '/app/workflow'
      path: '/workflow'
      fullPath: '/app/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bachs/webhook': {
      id: '/api/bachs/webhook'
      path: '/api/bachs/webhook'
      fullPath: '/api/bachs/webhook'
      preLoaderRoute: typeof ApiBachsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/goals/$goalId': {
      id: '/app/goals/$goalId'
      path: '/$goalId'
      fullPath: '/app/goals/$goalId'
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/goals/new': {
      id: '/app/goals/new'
      path: '/new'
      fullPath: '/app/goals/new'
      preLoaderRoute: typeof AppGoalsNewRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/'
      fullPath: '/app/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/app/workflows/new': {
      id: '/app/workflows/new'
      path: '/new'
      fullPath: '/app/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/app/goals/branch/$goalId': {
      id: '/app/goals/branch/$goalId'
      path: '/branch/$goalId'
      fullPath: '/app/goals/branch/$goalId'
      preLoaderRoute: typeof AppGoalsBranchGoalIdRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/workflow/$workflowId/': {
      id: '/app/workflow/$workflowId/'
      path: '/$workflowId'
      fullPath: '/app/workflow/$workflowId/'
      preLoaderRoute: typeof AppWorkflowWorkflowIdIndexRouteImport
      parentRoute: typeof AppWorkflowRoute
    }
    '/app/workflow/$workflowId/activities': {
      id: '/app/workflow/$workflowId/activities'
      path: '/$workflowId/activities'
      fullPath: '/app/workflow/$workflowId/activities'
      preLoaderRoute: typeof AppWorkflowWorkflowIdActivitiesRouteImport
      parentRoute: typeof AppWorkflowRoute
    }
  }
}

interface AppGoalsRouteChildren {
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute
  AppGoalsNewRoute: typeof AppGoalsNewRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppGoalsBranchGoalIdRoute: typeof AppGoalsBranchGoalIdRoute
}

const AppGoalsRouteChildren: AppGoalsRouteChildren = {
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
  AppGoalsNewRoute: AppGoalsNewRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppGoalsBranchGoalIdRoute: AppGoalsBranchGoalIdRoute,
}

const AppGoalsRouteWithChildren = AppGoalsRoute._addFileChildren(
  AppGoalsRouteChildren,
)

interface AppWorkflowRouteChildren {
  AppWorkflowWorkflowIdActivitiesRoute: typeof AppWorkflowWorkflowIdActivitiesRoute
  AppWorkflowWorkflowIdIndexRoute: typeof AppWorkflowWorkflowIdIndexRoute
}

const AppWorkflowRouteChildren: AppWorkflowRouteChildren = {
  AppWorkflowWorkflowIdActivitiesRoute: AppWorkflowWorkflowIdActivitiesRoute,
  AppWorkflowWorkflowIdIndexRoute: AppWorkflowWorkflowIdIndexRoute,
}

const AppWorkflowRouteWithChildren = AppWorkflowRoute._addFileChildren(
  AppWorkflowRouteChildren,
)

interface AppWorkflowsRouteChildren {
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppCreditsRoute: typeof AppCreditsRoute
  AppGoalsRoute: typeof AppGoalsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppWorkflowRoute: typeof AppWorkflowRouteWithChildren
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreditsRoute: AppCreditsRoute,
  AppGoalsRoute: AppGoalsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppWorkflowRoute: AppWorkflowRouteWithChildren,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  ApiBachsWebhookRoute: ApiBachsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
